name: Run Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        python-version: [3.8.10]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache dependency
        uses: actions/cache@v2
        id: cachepip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Install package
        run: sudo make install
      - name: Run Tests
        run: make test
